services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: ""
    startCommand: gunicorn your_project_name.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
staticPublishPath: staticfiles
