# Generated by Django 5.2.2 on 2025-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
